# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exam_management_system_development

test:
  <<: *default
  database: exam_management_system_test

production:
  <<: *default
  database: exam_management_system_production
  username: exam_management_system
  password: <%= ENV["EXAM_MANAGEMENT_SYSTEM_DATABASE_PASSWORD"] %>
